# SPDX-License-Identifier: Apache-2.0

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        tesseract-ocr \
        tesseract-ocr-spa \
        poppler-utils \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get install \
	tesseract-ocr \
	tesseract-ocr-spa \
	poppler-utils

RUN pip install --no-cache-dir \
	fastapi \
	"uvicorn[standard]" \
	python-dotenv \
	qdrant-client \
	psycopg2-binary \
	scikit-learn \
	requests \
	PyPDF2 \
	python-docx \
	pdf2image \
	pillow \
	pytesseract \
	openpyxl \
	python-pptx \
	google-genai

COPY . /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
